package com.lab.wisdom.mapper;

import com.lab.wisdom.model.wisdomLamp;
import com.lab.wisdom.model.wisdomLampExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface WisdomLampMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    long countByExample(wisdomLampExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    int deleteByExample(wisdomLampExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    int insert(wisdomLamp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    int insertSelective(wisdomLamp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    List<wisdomLamp> selectByExampleWithRowbounds(wisdomLampExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    List<wisdomLamp> selectByExample(wisdomLampExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    wisdomLamp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    int updateByExampleSelective(@Param("record") wisdomLamp record, @Param("example") wisdomLampExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    int updateByExample(@Param("record") wisdomLamp record, @Param("example") wisdomLampExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    int updateByPrimaryKeySelective(wisdomLamp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    int updateByPrimaryKey(wisdomLamp record);
}