package com.lab.wisdom.model;

public class wisdomLamp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wisdomlamp.id
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wisdomlamp.gmt_create
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    private String gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wisdomlamp.LED_Value
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    private Integer ledValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wisdomlamp.Hum
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    private Float hum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wisdomlamp.Tem
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    private Float tem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wisdomlamp.air
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    private String air;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wisdomlamp.LED_OnOff
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    private String ledOnoff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wisdomlamp.Buzzer_OnOff
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    private String buzzerOnoff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wisdomlamp.IfRain
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    private String ifrain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wisdomlamp.sunValue
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    private Integer sunvalue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wisdomlamp.id
     *
     * @return the value of wisdomlamp.id
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wisdomlamp.id
     *
     * @param id the value for wisdomlamp.id
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wisdomlamp.gmt_create
     *
     * @return the value of wisdomlamp.gmt_create
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public String getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wisdomlamp.gmt_create
     *
     * @param gmtCreate the value for wisdomlamp.gmt_create
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public void setGmtCreate(String gmtCreate) {
        this.gmtCreate = gmtCreate == null ? null : gmtCreate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wisdomlamp.LED_Value
     *
     * @return the value of wisdomlamp.LED_Value
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public Integer getLedValue() {
        return ledValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wisdomlamp.LED_Value
     *
     * @param ledValue the value for wisdomlamp.LED_Value
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public void setLedValue(Integer ledValue) {
        this.ledValue = ledValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wisdomlamp.Hum
     *
     * @return the value of wisdomlamp.Hum
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public Float getHum() {
        return hum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wisdomlamp.Hum
     *
     * @param hum the value for wisdomlamp.Hum
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public void setHum(Float hum) {
        this.hum = hum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wisdomlamp.Tem
     *
     * @return the value of wisdomlamp.Tem
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public Float getTem() {
        return tem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wisdomlamp.Tem
     *
     * @param tem the value for wisdomlamp.Tem
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public void setTem(Float tem) {
        this.tem = tem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wisdomlamp.air
     *
     * @return the value of wisdomlamp.air
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public String getAir() {
        return air;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wisdomlamp.air
     *
     * @param air the value for wisdomlamp.air
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public void setAir(String air) {
        this.air = air == null ? null : air.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wisdomlamp.LED_OnOff
     *
     * @return the value of wisdomlamp.LED_OnOff
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public String getLedOnoff() {
        return ledOnoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wisdomlamp.LED_OnOff
     *
     * @param ledOnoff the value for wisdomlamp.LED_OnOff
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public void setLedOnoff(String ledOnoff) {
        this.ledOnoff = ledOnoff == null ? null : ledOnoff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wisdomlamp.Buzzer_OnOff
     *
     * @return the value of wisdomlamp.Buzzer_OnOff
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public String getBuzzerOnoff() {
        return buzzerOnoff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wisdomlamp.Buzzer_OnOff
     *
     * @param buzzerOnoff the value for wisdomlamp.Buzzer_OnOff
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public void setBuzzerOnoff(String buzzerOnoff) {
        this.buzzerOnoff = buzzerOnoff == null ? null : buzzerOnoff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wisdomlamp.IfRain
     *
     * @return the value of wisdomlamp.IfRain
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public String getIfrain() {
        return ifrain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wisdomlamp.IfRain
     *
     * @param ifrain the value for wisdomlamp.IfRain
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public void setIfrain(String ifrain) {
        this.ifrain = ifrain == null ? null : ifrain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wisdomlamp.sunValue
     *
     * @return the value of wisdomlamp.sunValue
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public Integer getSunvalue() {
        return sunvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wisdomlamp.sunValue
     *
     * @param sunvalue the value for wisdomlamp.sunValue
     *
     * @mbg.generated Thu Mar 19 19:52:42 CST 2020
     */
    public void setSunvalue(Integer sunvalue) {
        this.sunvalue = sunvalue;
    }
}