package com.lab.wisdom.model;

import java.util.ArrayList;
import java.util.List;

public class wisdomLampExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    public wisdomLampExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNull() {
            addCriterion("gmt_create is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIsNotNull() {
            addCriterion("gmt_create is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreateEqualTo(String value) {
            addCriterion("gmt_create =", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotEqualTo(String value) {
            addCriterion("gmt_create <>", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThan(String value) {
            addCriterion("gmt_create >", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateGreaterThanOrEqualTo(String value) {
            addCriterion("gmt_create >=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThan(String value) {
            addCriterion("gmt_create <", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLessThanOrEqualTo(String value) {
            addCriterion("gmt_create <=", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateLike(String value) {
            addCriterion("gmt_create like", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotLike(String value) {
            addCriterion("gmt_create not like", value, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateIn(List<String> values) {
            addCriterion("gmt_create in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotIn(List<String> values) {
            addCriterion("gmt_create not in", values, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateBetween(String value1, String value2) {
            addCriterion("gmt_create between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andGmtCreateNotBetween(String value1, String value2) {
            addCriterion("gmt_create not between", value1, value2, "gmtCreate");
            return (Criteria) this;
        }

        public Criteria andLedValueIsNull() {
            addCriterion("LED_Value is null");
            return (Criteria) this;
        }

        public Criteria andLedValueIsNotNull() {
            addCriterion("LED_Value is not null");
            return (Criteria) this;
        }

        public Criteria andLedValueEqualTo(Integer value) {
            addCriterion("LED_Value =", value, "ledValue");
            return (Criteria) this;
        }

        public Criteria andLedValueNotEqualTo(Integer value) {
            addCriterion("LED_Value <>", value, "ledValue");
            return (Criteria) this;
        }

        public Criteria andLedValueGreaterThan(Integer value) {
            addCriterion("LED_Value >", value, "ledValue");
            return (Criteria) this;
        }

        public Criteria andLedValueGreaterThanOrEqualTo(Integer value) {
            addCriterion("LED_Value >=", value, "ledValue");
            return (Criteria) this;
        }

        public Criteria andLedValueLessThan(Integer value) {
            addCriterion("LED_Value <", value, "ledValue");
            return (Criteria) this;
        }

        public Criteria andLedValueLessThanOrEqualTo(Integer value) {
            addCriterion("LED_Value <=", value, "ledValue");
            return (Criteria) this;
        }

        public Criteria andLedValueIn(List<Integer> values) {
            addCriterion("LED_Value in", values, "ledValue");
            return (Criteria) this;
        }

        public Criteria andLedValueNotIn(List<Integer> values) {
            addCriterion("LED_Value not in", values, "ledValue");
            return (Criteria) this;
        }

        public Criteria andLedValueBetween(Integer value1, Integer value2) {
            addCriterion("LED_Value between", value1, value2, "ledValue");
            return (Criteria) this;
        }

        public Criteria andLedValueNotBetween(Integer value1, Integer value2) {
            addCriterion("LED_Value not between", value1, value2, "ledValue");
            return (Criteria) this;
        }

        public Criteria andHumIsNull() {
            addCriterion("Hum is null");
            return (Criteria) this;
        }

        public Criteria andHumIsNotNull() {
            addCriterion("Hum is not null");
            return (Criteria) this;
        }

        public Criteria andHumEqualTo(Float value) {
            addCriterion("Hum =", value, "hum");
            return (Criteria) this;
        }

        public Criteria andHumNotEqualTo(Float value) {
            addCriterion("Hum <>", value, "hum");
            return (Criteria) this;
        }

        public Criteria andHumGreaterThan(Float value) {
            addCriterion("Hum >", value, "hum");
            return (Criteria) this;
        }

        public Criteria andHumGreaterThanOrEqualTo(Float value) {
            addCriterion("Hum >=", value, "hum");
            return (Criteria) this;
        }

        public Criteria andHumLessThan(Float value) {
            addCriterion("Hum <", value, "hum");
            return (Criteria) this;
        }

        public Criteria andHumLessThanOrEqualTo(Float value) {
            addCriterion("Hum <=", value, "hum");
            return (Criteria) this;
        }

        public Criteria andHumIn(List<Float> values) {
            addCriterion("Hum in", values, "hum");
            return (Criteria) this;
        }

        public Criteria andHumNotIn(List<Float> values) {
            addCriterion("Hum not in", values, "hum");
            return (Criteria) this;
        }

        public Criteria andHumBetween(Float value1, Float value2) {
            addCriterion("Hum between", value1, value2, "hum");
            return (Criteria) this;
        }

        public Criteria andHumNotBetween(Float value1, Float value2) {
            addCriterion("Hum not between", value1, value2, "hum");
            return (Criteria) this;
        }

        public Criteria andTemIsNull() {
            addCriterion("Tem is null");
            return (Criteria) this;
        }

        public Criteria andTemIsNotNull() {
            addCriterion("Tem is not null");
            return (Criteria) this;
        }

        public Criteria andTemEqualTo(Float value) {
            addCriterion("Tem =", value, "tem");
            return (Criteria) this;
        }

        public Criteria andTemNotEqualTo(Float value) {
            addCriterion("Tem <>", value, "tem");
            return (Criteria) this;
        }

        public Criteria andTemGreaterThan(Float value) {
            addCriterion("Tem >", value, "tem");
            return (Criteria) this;
        }

        public Criteria andTemGreaterThanOrEqualTo(Float value) {
            addCriterion("Tem >=", value, "tem");
            return (Criteria) this;
        }

        public Criteria andTemLessThan(Float value) {
            addCriterion("Tem <", value, "tem");
            return (Criteria) this;
        }

        public Criteria andTemLessThanOrEqualTo(Float value) {
            addCriterion("Tem <=", value, "tem");
            return (Criteria) this;
        }

        public Criteria andTemIn(List<Float> values) {
            addCriterion("Tem in", values, "tem");
            return (Criteria) this;
        }

        public Criteria andTemNotIn(List<Float> values) {
            addCriterion("Tem not in", values, "tem");
            return (Criteria) this;
        }

        public Criteria andTemBetween(Float value1, Float value2) {
            addCriterion("Tem between", value1, value2, "tem");
            return (Criteria) this;
        }

        public Criteria andTemNotBetween(Float value1, Float value2) {
            addCriterion("Tem not between", value1, value2, "tem");
            return (Criteria) this;
        }

        public Criteria andAirIsNull() {
            addCriterion("air is null");
            return (Criteria) this;
        }

        public Criteria andAirIsNotNull() {
            addCriterion("air is not null");
            return (Criteria) this;
        }

        public Criteria andAirEqualTo(String value) {
            addCriterion("air =", value, "air");
            return (Criteria) this;
        }

        public Criteria andAirNotEqualTo(String value) {
            addCriterion("air <>", value, "air");
            return (Criteria) this;
        }

        public Criteria andAirGreaterThan(String value) {
            addCriterion("air >", value, "air");
            return (Criteria) this;
        }

        public Criteria andAirGreaterThanOrEqualTo(String value) {
            addCriterion("air >=", value, "air");
            return (Criteria) this;
        }

        public Criteria andAirLessThan(String value) {
            addCriterion("air <", value, "air");
            return (Criteria) this;
        }

        public Criteria andAirLessThanOrEqualTo(String value) {
            addCriterion("air <=", value, "air");
            return (Criteria) this;
        }

        public Criteria andAirLike(String value) {
            addCriterion("air like", value, "air");
            return (Criteria) this;
        }

        public Criteria andAirNotLike(String value) {
            addCriterion("air not like", value, "air");
            return (Criteria) this;
        }

        public Criteria andAirIn(List<String> values) {
            addCriterion("air in", values, "air");
            return (Criteria) this;
        }

        public Criteria andAirNotIn(List<String> values) {
            addCriterion("air not in", values, "air");
            return (Criteria) this;
        }

        public Criteria andAirBetween(String value1, String value2) {
            addCriterion("air between", value1, value2, "air");
            return (Criteria) this;
        }

        public Criteria andAirNotBetween(String value1, String value2) {
            addCriterion("air not between", value1, value2, "air");
            return (Criteria) this;
        }

        public Criteria andLedOnoffIsNull() {
            addCriterion("LED_OnOff is null");
            return (Criteria) this;
        }

        public Criteria andLedOnoffIsNotNull() {
            addCriterion("LED_OnOff is not null");
            return (Criteria) this;
        }

        public Criteria andLedOnoffEqualTo(String value) {
            addCriterion("LED_OnOff =", value, "ledOnoff");
            return (Criteria) this;
        }

        public Criteria andLedOnoffNotEqualTo(String value) {
            addCriterion("LED_OnOff <>", value, "ledOnoff");
            return (Criteria) this;
        }

        public Criteria andLedOnoffGreaterThan(String value) {
            addCriterion("LED_OnOff >", value, "ledOnoff");
            return (Criteria) this;
        }

        public Criteria andLedOnoffGreaterThanOrEqualTo(String value) {
            addCriterion("LED_OnOff >=", value, "ledOnoff");
            return (Criteria) this;
        }

        public Criteria andLedOnoffLessThan(String value) {
            addCriterion("LED_OnOff <", value, "ledOnoff");
            return (Criteria) this;
        }

        public Criteria andLedOnoffLessThanOrEqualTo(String value) {
            addCriterion("LED_OnOff <=", value, "ledOnoff");
            return (Criteria) this;
        }

        public Criteria andLedOnoffLike(String value) {
            addCriterion("LED_OnOff like", value, "ledOnoff");
            return (Criteria) this;
        }

        public Criteria andLedOnoffNotLike(String value) {
            addCriterion("LED_OnOff not like", value, "ledOnoff");
            return (Criteria) this;
        }

        public Criteria andLedOnoffIn(List<String> values) {
            addCriterion("LED_OnOff in", values, "ledOnoff");
            return (Criteria) this;
        }

        public Criteria andLedOnoffNotIn(List<String> values) {
            addCriterion("LED_OnOff not in", values, "ledOnoff");
            return (Criteria) this;
        }

        public Criteria andLedOnoffBetween(String value1, String value2) {
            addCriterion("LED_OnOff between", value1, value2, "ledOnoff");
            return (Criteria) this;
        }

        public Criteria andLedOnoffNotBetween(String value1, String value2) {
            addCriterion("LED_OnOff not between", value1, value2, "ledOnoff");
            return (Criteria) this;
        }

        public Criteria andBuzzerOnoffIsNull() {
            addCriterion("Buzzer_OnOff is null");
            return (Criteria) this;
        }

        public Criteria andBuzzerOnoffIsNotNull() {
            addCriterion("Buzzer_OnOff is not null");
            return (Criteria) this;
        }

        public Criteria andBuzzerOnoffEqualTo(String value) {
            addCriterion("Buzzer_OnOff =", value, "buzzerOnoff");
            return (Criteria) this;
        }

        public Criteria andBuzzerOnoffNotEqualTo(String value) {
            addCriterion("Buzzer_OnOff <>", value, "buzzerOnoff");
            return (Criteria) this;
        }

        public Criteria andBuzzerOnoffGreaterThan(String value) {
            addCriterion("Buzzer_OnOff >", value, "buzzerOnoff");
            return (Criteria) this;
        }

        public Criteria andBuzzerOnoffGreaterThanOrEqualTo(String value) {
            addCriterion("Buzzer_OnOff >=", value, "buzzerOnoff");
            return (Criteria) this;
        }

        public Criteria andBuzzerOnoffLessThan(String value) {
            addCriterion("Buzzer_OnOff <", value, "buzzerOnoff");
            return (Criteria) this;
        }

        public Criteria andBuzzerOnoffLessThanOrEqualTo(String value) {
            addCriterion("Buzzer_OnOff <=", value, "buzzerOnoff");
            return (Criteria) this;
        }

        public Criteria andBuzzerOnoffLike(String value) {
            addCriterion("Buzzer_OnOff like", value, "buzzerOnoff");
            return (Criteria) this;
        }

        public Criteria andBuzzerOnoffNotLike(String value) {
            addCriterion("Buzzer_OnOff not like", value, "buzzerOnoff");
            return (Criteria) this;
        }

        public Criteria andBuzzerOnoffIn(List<String> values) {
            addCriterion("Buzzer_OnOff in", values, "buzzerOnoff");
            return (Criteria) this;
        }

        public Criteria andBuzzerOnoffNotIn(List<String> values) {
            addCriterion("Buzzer_OnOff not in", values, "buzzerOnoff");
            return (Criteria) this;
        }

        public Criteria andBuzzerOnoffBetween(String value1, String value2) {
            addCriterion("Buzzer_OnOff between", value1, value2, "buzzerOnoff");
            return (Criteria) this;
        }

        public Criteria andBuzzerOnoffNotBetween(String value1, String value2) {
            addCriterion("Buzzer_OnOff not between", value1, value2, "buzzerOnoff");
            return (Criteria) this;
        }

        public Criteria andIfrainIsNull() {
            addCriterion("IfRain is null");
            return (Criteria) this;
        }

        public Criteria andIfrainIsNotNull() {
            addCriterion("IfRain is not null");
            return (Criteria) this;
        }

        public Criteria andIfrainEqualTo(String value) {
            addCriterion("IfRain =", value, "ifrain");
            return (Criteria) this;
        }

        public Criteria andIfrainNotEqualTo(String value) {
            addCriterion("IfRain <>", value, "ifrain");
            return (Criteria) this;
        }

        public Criteria andIfrainGreaterThan(String value) {
            addCriterion("IfRain >", value, "ifrain");
            return (Criteria) this;
        }

        public Criteria andIfrainGreaterThanOrEqualTo(String value) {
            addCriterion("IfRain >=", value, "ifrain");
            return (Criteria) this;
        }

        public Criteria andIfrainLessThan(String value) {
            addCriterion("IfRain <", value, "ifrain");
            return (Criteria) this;
        }

        public Criteria andIfrainLessThanOrEqualTo(String value) {
            addCriterion("IfRain <=", value, "ifrain");
            return (Criteria) this;
        }

        public Criteria andIfrainLike(String value) {
            addCriterion("IfRain like", value, "ifrain");
            return (Criteria) this;
        }

        public Criteria andIfrainNotLike(String value) {
            addCriterion("IfRain not like", value, "ifrain");
            return (Criteria) this;
        }

        public Criteria andIfrainIn(List<String> values) {
            addCriterion("IfRain in", values, "ifrain");
            return (Criteria) this;
        }

        public Criteria andIfrainNotIn(List<String> values) {
            addCriterion("IfRain not in", values, "ifrain");
            return (Criteria) this;
        }

        public Criteria andIfrainBetween(String value1, String value2) {
            addCriterion("IfRain between", value1, value2, "ifrain");
            return (Criteria) this;
        }

        public Criteria andIfrainNotBetween(String value1, String value2) {
            addCriterion("IfRain not between", value1, value2, "ifrain");
            return (Criteria) this;
        }

        public Criteria andSunvalueIsNull() {
            addCriterion("sunValue is null");
            return (Criteria) this;
        }

        public Criteria andSunvalueIsNotNull() {
            addCriterion("sunValue is not null");
            return (Criteria) this;
        }

        public Criteria andSunvalueEqualTo(Integer value) {
            addCriterion("sunValue =", value, "sunvalue");
            return (Criteria) this;
        }

        public Criteria andSunvalueNotEqualTo(Integer value) {
            addCriterion("sunValue <>", value, "sunvalue");
            return (Criteria) this;
        }

        public Criteria andSunvalueGreaterThan(Integer value) {
            addCriterion("sunValue >", value, "sunvalue");
            return (Criteria) this;
        }

        public Criteria andSunvalueGreaterThanOrEqualTo(Integer value) {
            addCriterion("sunValue >=", value, "sunvalue");
            return (Criteria) this;
        }

        public Criteria andSunvalueLessThan(Integer value) {
            addCriterion("sunValue <", value, "sunvalue");
            return (Criteria) this;
        }

        public Criteria andSunvalueLessThanOrEqualTo(Integer value) {
            addCriterion("sunValue <=", value, "sunvalue");
            return (Criteria) this;
        }

        public Criteria andSunvalueIn(List<Integer> values) {
            addCriterion("sunValue in", values, "sunvalue");
            return (Criteria) this;
        }

        public Criteria andSunvalueNotIn(List<Integer> values) {
            addCriterion("sunValue not in", values, "sunvalue");
            return (Criteria) this;
        }

        public Criteria andSunvalueBetween(Integer value1, Integer value2) {
            addCriterion("sunValue between", value1, value2, "sunvalue");
            return (Criteria) this;
        }

        public Criteria andSunvalueNotBetween(Integer value1, Integer value2) {
            addCriterion("sunValue not between", value1, value2, "sunvalue");
            return (Criteria) this;
        }

        public Criteria andRainValueIsNull() {
            addCriterion("rain_value is null");
            return (Criteria) this;
        }

        public Criteria andRainValueIsNotNull() {
            addCriterion("rain_value is not null");
            return (Criteria) this;
        }

        public Criteria andRainValueEqualTo(Float value) {
            addCriterion("rain_value =", value, "rainValue");
            return (Criteria) this;
        }

        public Criteria andRainValueNotEqualTo(Float value) {
            addCriterion("rain_value <>", value, "rainValue");
            return (Criteria) this;
        }

        public Criteria andRainValueGreaterThan(Float value) {
            addCriterion("rain_value >", value, "rainValue");
            return (Criteria) this;
        }

        public Criteria andRainValueGreaterThanOrEqualTo(Float value) {
            addCriterion("rain_value >=", value, "rainValue");
            return (Criteria) this;
        }

        public Criteria andRainValueLessThan(Float value) {
            addCriterion("rain_value <", value, "rainValue");
            return (Criteria) this;
        }

        public Criteria andRainValueLessThanOrEqualTo(Float value) {
            addCriterion("rain_value <=", value, "rainValue");
            return (Criteria) this;
        }

        public Criteria andRainValueIn(List<Float> values) {
            addCriterion("rain_value in", values, "rainValue");
            return (Criteria) this;
        }

        public Criteria andRainValueNotIn(List<Float> values) {
            addCriterion("rain_value not in", values, "rainValue");
            return (Criteria) this;
        }

        public Criteria andRainValueBetween(Float value1, Float value2) {
            addCriterion("rain_value between", value1, value2, "rainValue");
            return (Criteria) this;
        }

        public Criteria andRainValueNotBetween(Float value1, Float value2) {
            addCriterion("rain_value not between", value1, value2, "rainValue");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wisdomlamp
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 06 18:11:00 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wisdomlamp
     *
     * @mbg.generated Mon Jul 06 18:11:00 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}